name: "Azure Blob Storage Upload"
author: "tb <t.bauchspiess@ampeersenergy.de>"
description: "Uploads assets to Azure Blob Storage"

branding:
  icon: "box"
  color: "green"

inputs:
  connection_string:
    description: "The connection string for the storage account"
    required: true
  container_name:
    description: "The name of the storage account container these assets will be uploaded to"
    required: true
  source_path:
    description: "The name of the directory you want to upload"
    required: true
  destination_path:
    description: "The name of the directory you want to upload"
    required: true
  extra_args:
    description: "Extra arguments that can be passed to `az storage blob upload-batch`. Useful for passing flags like `--pattern`"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
